### ISSUE TITLE
Divergence from sourceforge

### ISSUE THREAD

**Issue by hjmjohnson** [DrJavaAtRice/drjava#5]
Hello,

I am reviewing code from https://sourceforge.net/p/drjava/git_repo/ci/master/tree/ and the version provided here.

Could you provide a little documentation abou the relationship between these two efforts?  Could that be added to a README.md file at the top level of the directory tree?

Thanks,
Hans

**Comment by ponderosaTX** [comment]
I revised the README file in the top level directory to answer your question.  I will try learn the .md formatting conventions and create an HTML version soon.
